/**
 * TRADE EDITOR — shared model.
 *
 * One source of truth for: section registry, field origins (source
 * awareness), read-only rules, structured psychology / mistake / playbook
 * payloads, and the narrative merge that keeps legacy columns mirrored.
 *
 * Every editor mode (quick, full, inline) reads from this module, so field
 * semantics can never drift between surfaces.
 */
import type { JournalEntry, EntryUpdate } from "@/lib/journal/api";
import { NARRATIVE_SECTIONS, readNarrative, type Narrative } from "@/lib/journal/narrative";

/* ------------------------------------------------------------------ */
/* Sections                                                            */
/* ------------------------------------------------------------------ */

export type SectionId =
  | "trade"
  | "plan"
  | "execution"
  | "review"
  | "psychology"
  | "playbook"
  | "mistakes"
  | "media"
  | "narrative"
  | "advanced";

export type SectionDef = {
  id: SectionId;
  label: string;
  hint: string;
  /** Extra search terms for ⌘K field search. */
  keywords: string[];
};

export const EDITOR_SECTIONS: SectionDef[] = [
  { id: "trade", label: "Trade", hint: "Identity, timing, classification", keywords: ["symbol", "pair", "direction", "long", "short", "session", "setup", "strategy", "tags", "status", "account", "date"] },
  { id: "plan", label: "Plan", hint: "What you intended before entry", keywords: ["stop", "sl", "target", "tp", "risk", "rr", "invalidation", "confidence", "entry conditions"] },
  { id: "execution", label: "Execution", hint: "What actually happened", keywords: ["entry", "exit", "quantity", "lot", "fees", "commission", "swap", "pnl", "gross", "net", "duration"] },
  { id: "review", label: "Review", hint: "Grade and self-rating", keywords: ["grade", "result", "exit reason", "well", "wrong", "learned", "discipline", "execution score", "patience"] },
  { id: "psychology", label: "Psychology", hint: "Before, during and after", keywords: ["mood", "stress", "fear", "fomo", "greed", "revenge", "regret", "calm", "emotion"] },
  { id: "playbook", label: "Playbook", hint: "Rules followed or broken", keywords: ["playbook", "rules", "checklist", "verdict", "example"] },
  { id: "mistakes", label: "Mistakes", hint: "Tagged errors and their cost", keywords: ["mistake", "error", "severity", "cost", "evidence"] },
  { id: "media", label: "Media", hint: "Screenshots and attachments", keywords: ["screenshot", "image", "upload", "attachment", "file", "evidence"] },
  { id: "narrative", label: "Narrative", hint: "The written story", keywords: ["thesis", "notes", "story", "saw", "did", "learned", "rule"] },
  { id: "advanced", label: "Advanced", hint: "Source data and corrections", keywords: ["broker", "import", "raw", "timezone", "currency", "share", "danger"] },
];

/** Fields that live in the quick editor (progressive disclosure default). */
export const QUICK_FIELDS = [
  "setup",
  "tags",
  "mistakes",
  "emotions",
  "grade",
  "notes",
  "screenshot",
  "playbook",
  "exit_reason",
] as const;

/* ------------------------------------------------------------------ */
/* Source awareness                                                    */
/* ------------------------------------------------------------------ */

export type FieldSource =
  | "manual"
  | "imported"
  | "synced"
  | "replay"
  | "calculated"
  | "ai"
  | "corrected";

export const SOURCE_LABEL: Record<FieldSource, string> = {
  manual: "Entered by you",
  imported: "Imported from a file",
  synced: "Synced from your broker/account",
  replay: "Generated by Replay Studio",
  calculated: "Calculated from other fields",
  ai: "Suggested by AI — confirm before trusting",
  corrected: "Manually corrected",
};

/** Execution facts owned by an upstream trade record. */
export const EXECUTION_FACT_FIELDS = [
  "entry_price",
  "exit_price",
  "lot_size",
  "pnl",
  "commission",
  "swap",
  "opened_at",
  "closed_at",
  "direction",
  "symbol",
] as const;

/** Values the platform derives — never silently user-owned. */
export const CALCULATED_FIELDS = ["rr", "reward_pct", "duration_seconds", "word_count"] as const;

export type EntryOrigin = "manual" | "imported" | "synced" | "replay";

/** Where the row as a whole came from. Derived, never guessed at render time. */
export function entryOrigin(entry: JournalEntry): EntryOrigin {
  const sources = readJson<Record<string, FieldSource | string>>(entry, "field_sources");
  const declared = sources.__origin;
  if (declared === "imported" || declared === "replay" || declared === "synced" || declared === "manual") {
    return declared;
  }
  if (entry.trade_id) return "synced";
  return "manual";
}

export const ORIGIN_LABEL: Record<EntryOrigin, string> = {
  manual: "Manual",
  imported: "Imported",
  synced: "Broker synced",
  replay: "Replay",
};

/** Per-field origin, honouring stored overrides first. */
export function fieldSource(entry: JournalEntry, field: string): FieldSource {
  const stored = readJson<Record<string, FieldSource>>(entry, "field_sources")[field];
  if (stored) return stored;
  if ((CALCULATED_FIELDS as readonly string[]).includes(field)) return "calculated";
  const origin = entryOrigin(entry);
  if (origin !== "manual" && (EXECUTION_FACT_FIELDS as readonly string[]).includes(field)) {
    return origin === "imported" ? "imported" : origin === "replay" ? "replay" : "synced";
  }
  return "manual";
}

/**
 * Locked = upstream owns the value. Unlocking is explicit and recorded, so a
 * broker sync is never silently overwritten by a stray keystroke.
 */
export function isFieldLocked(entry: JournalEntry, field: string, correctionsUnlocked: boolean): boolean {
  if (correctionsUnlocked) return false;
  const src = fieldSource(entry, field);
  if (src === "corrected" || src === "manual") return false;
  if (src === "calculated") return true;
  return (EXECUTION_FACT_FIELDS as readonly string[]).includes(field);
}

/* ------------------------------------------------------------------ */
/* JSON payloads                                                       */
/* ------------------------------------------------------------------ */

export function readJson<T extends object>(entry: JournalEntry, key: string): T {
  const raw = (entry as unknown as Record<string, unknown>)[key];
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {} as T;
  return raw as T;
}

/* Psychology --------------------------------------------------------- */

export type PsychStage = "before" | "during" | "after";

export type PsychologyState = {
  before?: string[];
  during?: string[];
  after?: string[];
  /** chip value -> 1..3 intensity */
  intensity?: Record<string, number>;
  notes?: Partial<Record<PsychStage, string>>;
};

export const PSYCH_CHIPS: Record<PsychStage, { value: string; label: string }[]> = {
  before: [
    { value: "calm", label: "Calm" },
    { value: "confident", label: "Confident" },
    { value: "stressed", label: "Stressed" },
    { value: "fear", label: "Fear" },
    { value: "fomo", label: "FOMO" },
    { value: "low_energy", label: "Low energy" },
    { value: "focused", label: "Focused" },
    { value: "distracted", label: "Distracted" },
  ],
  during: [
    { value: "hesitation", label: "Hesitation" },
    { value: "greed", label: "Greed" },
    { value: "revenge", label: "Revenge" },
    { value: "anxiety", label: "Anxiety" },
    { value: "impulsive", label: "Impulsive" },
    { value: "patient", label: "Patient" },
    { value: "in_control", label: "In control" },
  ],
  after: [
    { value: "satisfied", label: "Satisfied" },
    { value: "frustrated", label: "Frustrated" },
    { value: "regret", label: "Regret" },
    { value: "calm_after", label: "Calm" },
    { value: "disciplined", label: "Disciplined" },
    { value: "relieved", label: "Relieved" },
  ],
};

export const PSYCH_STAGE_LABEL: Record<PsychStage, string> = {
  before: "Before the trade",
  during: "In the trade",
  after: "After the trade",
};

export function readPsychology(entry: JournalEntry): PsychologyState {
  return readJson<PsychologyState>(entry, "psychology");
}

/* Mistakes ----------------------------------------------------------- */

export type MistakeSeverity = "low" | "medium" | "high";
export type MistakeDetectionSource = "user" | "rule" | "ai";

export type MistakeDetail = {
  severity?: MistakeSeverity;
  evidence?: string;
  cost?: number | null;
  note?: string;
  source?: MistakeDetectionSource;
  /** AI/rule suggestions only count once the trader confirms them. */
  confirmed?: boolean;
};

export type MistakeDetailMap = Record<string, MistakeDetail>;

export const MISTAKE_CATEGORIES = [
  "setup",
  "entry",
  "risk",
  "management",
  "exit",
  "psychology",
  "process",
] as const;

export type MistakeCategory = (typeof MISTAKE_CATEGORIES)[number];

export const MISTAKE_CATALOG: { value: string; label: string; category: MistakeCategory }[] = [
  { value: "no_setup", label: "No valid setup", category: "setup" },
  { value: "wrong_session", label: "Wrong session", category: "setup" },
  { value: "counter_trend", label: "Traded against trend", category: "setup" },
  { value: "entered_early", label: "Entered early", category: "entry" },
  { value: "entered_late", label: "Entered late", category: "entry" },
  { value: "missed_confirmation", label: "Missed confirmation", category: "entry" },
  { value: "chased_price", label: "Chased price", category: "entry" },
  { value: "no_stop_loss", label: "No stop loss", category: "risk" },
  { value: "over_leveraged", label: "Over leveraged", category: "risk" },
  { value: "poor_risk_mgmt", label: "Poor risk sizing", category: "risk" },
  { value: "risk_too_small", label: "Risk far below plan", category: "risk" },
  { value: "moved_stop_loss", label: "Moved stop loss", category: "management" },
  { value: "removed_stop", label: "Removed stop", category: "management" },
  { value: "added_to_loser", label: "Added to a loser", category: "management" },
  { value: "no_breakeven", label: "Never moved to break-even", category: "management" },
  { value: "exited_early", label: "Exited early", category: "exit" },
  { value: "held_too_long", label: "Held too long", category: "exit" },
  { value: "ignored_target", label: "Ignored target", category: "exit" },
  { value: "revenge_trade", label: "Revenge trade", category: "psychology" },
  { value: "fomo_entry", label: "FOMO entry", category: "psychology" },
  { value: "overtrading", label: "Overtrading", category: "psychology" },
  { value: "hesitated", label: "Hesitated on a valid signal", category: "psychology" },
  { value: "ignored_plan", label: "Ignored the plan", category: "process" },
  { value: "no_journal", label: "Did not journal in time", category: "process" },
  { value: "no_screenshot", label: "No screenshot evidence", category: "process" },
];

export const MISTAKE_CATEGORY_LABEL: Record<MistakeCategory, string> = {
  setup: "Setup",
  entry: "Entry",
  risk: "Risk",
  management: "Management",
  exit: "Exit",
  psychology: "Psychology",
  process: "Process",
};

export function mistakeCatalogLabel(value: string): string {
  return (
    MISTAKE_CATALOG.find((m) => m.value === value)?.label ??
    value.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase())
  );
}

export function readMistakeDetails(entry: JournalEntry): MistakeDetailMap {
  const raw = (entry as unknown as Record<string, unknown>).mistake_flags;
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return {};
  return raw as MistakeDetailMap;
}

/* Playbook ----------------------------------------------------------- */

export type RuleState = "followed" | "missed" | "broken";

export type PlaybookReview = {
  playbook?: string | null;
  /** rule id -> the trader's corrected verdict (overrides the system verdict) */
  overrides?: Record<string, RuleState>;
  evidence?: Record<string, string>;
  isExample?: boolean;
};

export function readPlaybookReview(entry: JournalEntry): PlaybookReview {
  return readJson<PlaybookReview>(entry, "playbook_review");
}

/* ------------------------------------------------------------------ */
/* Narrative merge (keeps legacy mirrors intact)                       */
/* ------------------------------------------------------------------ */

export const NARRATIVE_KEYS = NARRATIVE_SECTIONS.map((s) => s.key);

/**
 * Merge narrative changes without dropping unknown keys written by other
 * surfaces, and mirror thesis/free onto the legacy text columns.
 */
export function narrativePatch(entry: JournalEntry, patch: Narrative): EntryUpdate {
  const existingRaw = readJson<Record<string, unknown>>(entry, "narrative");
  const next = { ...existingRaw, ...readNarrative(entry), ...patch };
  const update: EntryUpdate = { narrative: next as unknown as EntryUpdate["narrative"] };
  if ("thesis" in patch) update.entry_reason_text = patch.thesis ?? null;
  if ("free" in patch) {
    update.notes_text = patch.free ?? null;
    update.word_count = (patch.free ?? "").trim().split(/\s+/).filter(Boolean).length;
  }
  return update;
}

/* ------------------------------------------------------------------ */
/* Misc helpers                                                        */
/* ------------------------------------------------------------------ */

export function computeDurationSeconds(
  open: string | null | undefined,
  close: string | null | undefined,
): number | null {
  if (!open || !close) return null;
  const s = Math.round((new Date(close).getTime() - new Date(open).getTime()) / 1000);
  return Number.isFinite(s) ? Math.max(0, s) : null;
}

/**
 * Structured plan/review values that have no dedicated column. They live in
 * the narrative jsonb under an `x` namespace so nothing new is migrated and
 * legacy readers (which only look at known narrative keys) stay unaffected.
 */
export type EditorExtras = {
  planned_entry?: number | null;
  risk_amount?: number | null;
  expected_rr?: number | null;
  invalidation?: string;
  management_plan?: string;
  entry_conditions?: string;
  exit_reason?: string;
  result?: string;
  timezone?: string;
  currency?: string;
  asset_class?: string;
  account_label?: string;
  broker_ref?: string;
  corrections_note?: string;
};

export function readExtras(entry: JournalEntry): EditorExtras {
  const nar = readJson<Record<string, unknown>>(entry, "narrative");
  const x = nar.x;
  if (!x || typeof x !== "object" || Array.isArray(x)) return {};
  return x as EditorExtras;
}

export function extrasPatch(entry: JournalEntry, patch: EditorExtras): EntryUpdate {
  const nar = readJson<Record<string, unknown>>(entry, "narrative");
  const next = { ...nar, x: { ...readExtras(entry), ...patch } };
  return { narrative: next as unknown as EntryUpdate["narrative"] };
}

export const EXIT_REASONS = [
  { value: "target", label: "Target hit" },
  { value: "stop", label: "Stop hit" },
  { value: "manual", label: "Manual close" },
  { value: "breakeven", label: "Break-even stop" },
  { value: "trail", label: "Trailing stop" },
  { value: "time", label: "Time-based exit" },
  { value: "news", label: "News / risk event" },
  { value: "invalidation", label: "Thesis invalidated" },
];
