/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReplayRouteImport } from './routes/_authenticated/replay'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaperTradingRouteImport } from './routes/_authenticated/paper-trading'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedStrategiesIndexRouteImport } from './routes/_authenticated/strategies.index'
import { Route as AuthenticatedStatisticsIndexRouteImport } from './routes/_authenticated/statistics.index'
import { Route as AuthenticatedReplayIndexRouteImport } from './routes/_authenticated/replay.index'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market.index'
import { Route as AuthenticatedLeaderboardIndexRouteImport } from './routes/_authenticated/leaderboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as JournalShareTokenRouteImport } from './routes/journal.share.$token'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthenticatedStrategiesTemplatesRouteImport } from './routes/_authenticated/strategies.templates'
import { Route as AuthenticatedStrategiesSharedRouteImport } from './routes/_authenticated/strategies.shared'
import { Route as AuthenticatedStrategiesSettingsRouteImport } from './routes/_authenticated/strategies.settings'
import { Route as AuthenticatedStrategiesPlaybooksRouteImport } from './routes/_authenticated/strategies.playbooks'
import { Route as AuthenticatedStrategiesLibraryRouteImport } from './routes/_authenticated/strategies.library'
import { Route as AuthenticatedStrategiesCreateRouteImport } from './routes/_authenticated/strategies.create'
import { Route as AuthenticatedStrategiesBacktestsRouteImport } from './routes/_authenticated/strategies.backtests'
import { Route as AuthenticatedStrategiesIdRouteImport } from './routes/_authenticated/strategies.$id'
import { Route as AuthenticatedStatisticsSetupsRouteImport } from './routes/_authenticated/statistics.setups'
import { Route as AuthenticatedStatisticsSessionsRouteImport } from './routes/_authenticated/statistics.sessions'
import { Route as AuthenticatedStatisticsRiskRouteImport } from './routes/_authenticated/statistics.risk'
import { Route as AuthenticatedStatisticsReportsRouteImport } from './routes/_authenticated/statistics.reports'
import { Route as AuthenticatedStatisticsPerformanceRouteImport } from './routes/_authenticated/statistics.performance'
import { Route as AuthenticatedStatisticsCalendarRouteImport } from './routes/_authenticated/statistics.calendar'
import { Route as AuthenticatedReplayTradesRouteImport } from './routes/_authenticated/replay.trades'
import { Route as AuthenticatedReplaySettingsRouteImport } from './routes/_authenticated/replay.settings'
import { Route as AuthenticatedReplaySessionRouteImport } from './routes/_authenticated/replay.session'
import { Route as AuthenticatedReplayLibraryRouteImport } from './routes/_authenticated/replay.library'
import { Route as AuthenticatedProfileUsernameRouteImport } from './routes/_authenticated/profile.$username'
import { Route as AuthenticatedMarketSymbolsRouteImport } from './routes/_authenticated/market.symbols'
import { Route as AuthenticatedMarketSettingsRouteImport } from './routes/_authenticated/market.settings'
import { Route as AuthenticatedMarketSessionsRouteImport } from './routes/_authenticated/market.sessions'
import { Route as AuthenticatedMarketProvidersRouteImport } from './routes/_authenticated/market.providers'
import { Route as AuthenticatedMarketAlertsRouteImport } from './routes/_authenticated/market.alerts'
import { Route as AuthenticatedLeaderboardLeagueRouteImport } from './routes/_authenticated/leaderboard.league'
import { Route as AuthenticatedLeaderboardGlobalRouteImport } from './routes/_authenticated/leaderboard.global'
import { Route as AuthenticatedLeaderboardFriendsRouteImport } from './routes/_authenticated/leaderboard.friends'
import { Route as AuthenticatedLeaderboardCountryRouteImport } from './routes/_authenticated/leaderboard.country'
import { Route as AuthenticatedChallengesRewardsRouteImport } from './routes/_authenticated/challenges/rewards'
import { Route as AuthenticatedChallengesHistoryRouteImport } from './routes/_authenticated/challenges/history'
import { Route as AuthenticatedAiTradeReviewRouteImport } from './routes/_authenticated/ai.trade-review'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai.settings'
import { Route as AuthenticatedAiPsychologyRouteImport } from './routes/_authenticated/ai.psychology'
import { Route as AuthenticatedAiPlaybooksRouteImport } from './routes/_authenticated/ai.playbooks'
import { Route as AuthenticatedAiPerformanceRouteImport } from './routes/_authenticated/ai.performance'
import { Route as AuthenticatedAiHistoryRouteImport } from './routes/_authenticated/ai.history'
import { Route as AuthenticatedAiDashboardRouteImport } from './routes/_authenticated/ai.dashboard'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated/ai.chat'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTradesRouteImport } from './routes/_authenticated/admin.trades'
import { Route as AuthenticatedAdminStorageRouteImport } from './routes/_authenticated/admin.storage'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminMarketDataRouteImport } from './routes/_authenticated/admin.market-data'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminLeaderboardsRouteImport } from './routes/_authenticated/admin.leaderboards'
import { Route as AuthenticatedAdminJournalRouteImport } from './routes/_authenticated/admin.journal'
import { Route as AuthenticatedAdminFeatureFlagsRouteImport } from './routes/_authenticated/admin.feature-flags'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminChallengesRouteImport } from './routes/_authenticated/admin.challenges'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAchievementsRouteImport } from './routes/_authenticated/admin.achievements'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReplayRoute = AuthenticatedReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaperTradingRoute =
  AuthenticatedPaperTradingRouteImport.update({
    id: '/paper-trading',
    path: '/paper-trading',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStrategiesIndexRoute =
  AuthenticatedStrategiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStatisticsIndexRoute =
  AuthenticatedStatisticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedReplayIndexRoute =
  AuthenticatedReplayIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReplayRoute,
  } as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedLeaderboardIndexRoute =
  AuthenticatedLeaderboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const JournalShareTokenRoute = JournalShareTokenRouteImport.update({
  id: '/journal/share/$token',
  path: '/journal/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiesTemplatesRoute =
  AuthenticatedStrategiesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesSharedRoute =
  AuthenticatedStrategiesSharedRouteImport.update({
    id: '/shared',
    path: '/shared',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesSettingsRoute =
  AuthenticatedStrategiesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesPlaybooksRoute =
  AuthenticatedStrategiesPlaybooksRouteImport.update({
    id: '/playbooks',
    path: '/playbooks',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesLibraryRoute =
  AuthenticatedStrategiesLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesCreateRoute =
  AuthenticatedStrategiesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesBacktestsRoute =
  AuthenticatedStrategiesBacktestsRouteImport.update({
    id: '/backtests',
    path: '/backtests',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStrategiesIdRoute =
  AuthenticatedStrategiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedStrategiesRoute,
  } as any)
const AuthenticatedStatisticsSetupsRoute =
  AuthenticatedStatisticsSetupsRouteImport.update({
    id: '/setups',
    path: '/setups',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedStatisticsSessionsRoute =
  AuthenticatedStatisticsSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedStatisticsRiskRoute =
  AuthenticatedStatisticsRiskRouteImport.update({
    id: '/risk',
    path: '/risk',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedStatisticsReportsRoute =
  AuthenticatedStatisticsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedStatisticsPerformanceRoute =
  AuthenticatedStatisticsPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedStatisticsCalendarRoute =
  AuthenticatedStatisticsCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedStatisticsRoute,
  } as any)
const AuthenticatedReplayTradesRoute =
  AuthenticatedReplayTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedReplayRoute,
  } as any)
const AuthenticatedReplaySettingsRoute =
  AuthenticatedReplaySettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedReplayRoute,
  } as any)
const AuthenticatedReplaySessionRoute =
  AuthenticatedReplaySessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => AuthenticatedReplayRoute,
  } as any)
const AuthenticatedReplayLibraryRoute =
  AuthenticatedReplayLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedReplayRoute,
  } as any)
const AuthenticatedProfileUsernameRoute =
  AuthenticatedProfileUsernameRouteImport.update({
    id: '/$username',
    path: '/$username',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedMarketSymbolsRoute =
  AuthenticatedMarketSymbolsRouteImport.update({
    id: '/symbols',
    path: '/symbols',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedMarketSettingsRoute =
  AuthenticatedMarketSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedMarketSessionsRoute =
  AuthenticatedMarketSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedMarketProvidersRoute =
  AuthenticatedMarketProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedMarketAlertsRoute =
  AuthenticatedMarketAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedLeaderboardLeagueRoute =
  AuthenticatedLeaderboardLeagueRouteImport.update({
    id: '/league',
    path: '/league',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedLeaderboardGlobalRoute =
  AuthenticatedLeaderboardGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedLeaderboardFriendsRoute =
  AuthenticatedLeaderboardFriendsRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedLeaderboardCountryRoute =
  AuthenticatedLeaderboardCountryRouteImport.update({
    id: '/country',
    path: '/country',
    getParentRoute: () => AuthenticatedLeaderboardRoute,
  } as any)
const AuthenticatedChallengesRewardsRoute =
  AuthenticatedChallengesRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const AuthenticatedChallengesHistoryRoute =
  AuthenticatedChallengesHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedChallengesRoute,
  } as any)
const AuthenticatedAiTradeReviewRoute =
  AuthenticatedAiTradeReviewRouteImport.update({
    id: '/trade-review',
    path: '/trade-review',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiPsychologyRoute =
  AuthenticatedAiPsychologyRouteImport.update({
    id: '/psychology',
    path: '/psychology',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiPlaybooksRoute =
  AuthenticatedAiPlaybooksRouteImport.update({
    id: '/playbooks',
    path: '/playbooks',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiPerformanceRoute =
  AuthenticatedAiPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiHistoryRoute = AuthenticatedAiHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAiDashboardRoute =
  AuthenticatedAiDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAiRoute,
  } as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAiRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTradesRoute =
  AuthenticatedAdminTradesRouteImport.update({
    id: '/trades',
    path: '/trades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStorageRoute =
  AuthenticatedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketDataRoute =
  AuthenticatedAdminMarketDataRouteImport.update({
    id: '/market-data',
    path: '/market-data',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeaderboardsRoute =
  AuthenticatedAdminLeaderboardsRouteImport.update({
    id: '/leaderboards',
    path: '/leaderboards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJournalRoute =
  AuthenticatedAdminJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeatureFlagsRoute =
  AuthenticatedAdminFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChallengesRoute =
  AuthenticatedAdminChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAchievementsRoute =
  AuthenticatedAdminAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai': typeof AuthenticatedAiRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/paper-trading': typeof AuthenticatedPaperTradingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/replay': typeof AuthenticatedReplayRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/statistics': typeof AuthenticatedStatisticsRouteWithChildren
  '/strategies': typeof AuthenticatedStrategiesRouteWithChildren
  '/support': typeof AuthenticatedSupportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/achievements': typeof AuthenticatedAdminAchievementsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/leaderboards': typeof AuthenticatedAdminLeaderboardsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/market-data': typeof AuthenticatedAdminMarketDataRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ai/chat': typeof AuthenticatedAiChatRoute
  '/ai/dashboard': typeof AuthenticatedAiDashboardRoute
  '/ai/history': typeof AuthenticatedAiHistoryRoute
  '/ai/performance': typeof AuthenticatedAiPerformanceRoute
  '/ai/playbooks': typeof AuthenticatedAiPlaybooksRoute
  '/ai/psychology': typeof AuthenticatedAiPsychologyRoute
  '/ai/settings': typeof AuthenticatedAiSettingsRoute
  '/ai/trade-review': typeof AuthenticatedAiTradeReviewRoute
  '/challenges/history': typeof AuthenticatedChallengesHistoryRoute
  '/challenges/rewards': typeof AuthenticatedChallengesRewardsRoute
  '/leaderboard/country': typeof AuthenticatedLeaderboardCountryRoute
  '/leaderboard/friends': typeof AuthenticatedLeaderboardFriendsRoute
  '/leaderboard/global': typeof AuthenticatedLeaderboardGlobalRoute
  '/leaderboard/league': typeof AuthenticatedLeaderboardLeagueRoute
  '/market/alerts': typeof AuthenticatedMarketAlertsRoute
  '/market/providers': typeof AuthenticatedMarketProvidersRoute
  '/market/sessions': typeof AuthenticatedMarketSessionsRoute
  '/market/settings': typeof AuthenticatedMarketSettingsRoute
  '/market/symbols': typeof AuthenticatedMarketSymbolsRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/replay/library': typeof AuthenticatedReplayLibraryRoute
  '/replay/session': typeof AuthenticatedReplaySessionRoute
  '/replay/settings': typeof AuthenticatedReplaySettingsRoute
  '/replay/trades': typeof AuthenticatedReplayTradesRoute
  '/statistics/calendar': typeof AuthenticatedStatisticsCalendarRoute
  '/statistics/performance': typeof AuthenticatedStatisticsPerformanceRoute
  '/statistics/reports': typeof AuthenticatedStatisticsReportsRoute
  '/statistics/risk': typeof AuthenticatedStatisticsRiskRoute
  '/statistics/sessions': typeof AuthenticatedStatisticsSessionsRoute
  '/statistics/setups': typeof AuthenticatedStatisticsSetupsRoute
  '/strategies/$id': typeof AuthenticatedStrategiesIdRoute
  '/strategies/backtests': typeof AuthenticatedStrategiesBacktestsRoute
  '/strategies/create': typeof AuthenticatedStrategiesCreateRoute
  '/strategies/library': typeof AuthenticatedStrategiesLibraryRoute
  '/strategies/playbooks': typeof AuthenticatedStrategiesPlaybooksRoute
  '/strategies/settings': typeof AuthenticatedStrategiesSettingsRoute
  '/strategies/shared': typeof AuthenticatedStrategiesSharedRoute
  '/strategies/templates': typeof AuthenticatedStrategiesTemplatesRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/journal/share/$token': typeof JournalShareTokenRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
  '/replay/': typeof AuthenticatedReplayIndexRoute
  '/statistics/': typeof AuthenticatedStatisticsIndexRoute
  '/strategies/': typeof AuthenticatedStrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/ai': typeof AuthenticatedAiRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/paper-trading': typeof AuthenticatedPaperTradingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/users': typeof AuthenticatedUsersRoute
  '/admin/achievements': typeof AuthenticatedAdminAchievementsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/admin/leaderboards': typeof AuthenticatedAdminLeaderboardsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/market-data': typeof AuthenticatedAdminMarketDataRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ai/chat': typeof AuthenticatedAiChatRoute
  '/ai/dashboard': typeof AuthenticatedAiDashboardRoute
  '/ai/history': typeof AuthenticatedAiHistoryRoute
  '/ai/performance': typeof AuthenticatedAiPerformanceRoute
  '/ai/playbooks': typeof AuthenticatedAiPlaybooksRoute
  '/ai/psychology': typeof AuthenticatedAiPsychologyRoute
  '/ai/settings': typeof AuthenticatedAiSettingsRoute
  '/ai/trade-review': typeof AuthenticatedAiTradeReviewRoute
  '/challenges/history': typeof AuthenticatedChallengesHistoryRoute
  '/challenges/rewards': typeof AuthenticatedChallengesRewardsRoute
  '/leaderboard/country': typeof AuthenticatedLeaderboardCountryRoute
  '/leaderboard/friends': typeof AuthenticatedLeaderboardFriendsRoute
  '/leaderboard/global': typeof AuthenticatedLeaderboardGlobalRoute
  '/leaderboard/league': typeof AuthenticatedLeaderboardLeagueRoute
  '/market/alerts': typeof AuthenticatedMarketAlertsRoute
  '/market/providers': typeof AuthenticatedMarketProvidersRoute
  '/market/sessions': typeof AuthenticatedMarketSessionsRoute
  '/market/settings': typeof AuthenticatedMarketSettingsRoute
  '/market/symbols': typeof AuthenticatedMarketSymbolsRoute
  '/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/replay/library': typeof AuthenticatedReplayLibraryRoute
  '/replay/session': typeof AuthenticatedReplaySessionRoute
  '/replay/settings': typeof AuthenticatedReplaySettingsRoute
  '/replay/trades': typeof AuthenticatedReplayTradesRoute
  '/statistics/calendar': typeof AuthenticatedStatisticsCalendarRoute
  '/statistics/performance': typeof AuthenticatedStatisticsPerformanceRoute
  '/statistics/reports': typeof AuthenticatedStatisticsReportsRoute
  '/statistics/risk': typeof AuthenticatedStatisticsRiskRoute
  '/statistics/sessions': typeof AuthenticatedStatisticsSessionsRoute
  '/statistics/setups': typeof AuthenticatedStatisticsSetupsRoute
  '/strategies/$id': typeof AuthenticatedStrategiesIdRoute
  '/strategies/backtests': typeof AuthenticatedStrategiesBacktestsRoute
  '/strategies/create': typeof AuthenticatedStrategiesCreateRoute
  '/strategies/library': typeof AuthenticatedStrategiesLibraryRoute
  '/strategies/playbooks': typeof AuthenticatedStrategiesPlaybooksRoute
  '/strategies/settings': typeof AuthenticatedStrategiesSettingsRoute
  '/strategies/shared': typeof AuthenticatedStrategiesSharedRoute
  '/strategies/templates': typeof AuthenticatedStrategiesTemplatesRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/journal/share/$token': typeof JournalShareTokenRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/leaderboard': typeof AuthenticatedLeaderboardIndexRoute
  '/market': typeof AuthenticatedMarketIndexRoute
  '/replay': typeof AuthenticatedReplayIndexRoute
  '/statistics': typeof AuthenticatedStatisticsIndexRoute
  '/strategies': typeof AuthenticatedStrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ai': typeof AuthenticatedAiRouteWithChildren
  '/_authenticated/challenges': typeof AuthenticatedChallengesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRouteWithChildren
  '/_authenticated/market': typeof AuthenticatedMarketRouteWithChildren
  '/_authenticated/paper-trading': typeof AuthenticatedPaperTradingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/replay': typeof AuthenticatedReplayRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRouteWithChildren
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRouteWithChildren
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/admin/achievements': typeof AuthenticatedAdminAchievementsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/challenges': typeof AuthenticatedAdminChallengesRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/feature-flags': typeof AuthenticatedAdminFeatureFlagsRoute
  '/_authenticated/admin/journal': typeof AuthenticatedAdminJournalRoute
  '/_authenticated/admin/leaderboards': typeof AuthenticatedAdminLeaderboardsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/market-data': typeof AuthenticatedAdminMarketDataRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/storage': typeof AuthenticatedAdminStorageRoute
  '/_authenticated/admin/trades': typeof AuthenticatedAdminTradesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/ai/chat': typeof AuthenticatedAiChatRoute
  '/_authenticated/ai/dashboard': typeof AuthenticatedAiDashboardRoute
  '/_authenticated/ai/history': typeof AuthenticatedAiHistoryRoute
  '/_authenticated/ai/performance': typeof AuthenticatedAiPerformanceRoute
  '/_authenticated/ai/playbooks': typeof AuthenticatedAiPlaybooksRoute
  '/_authenticated/ai/psychology': typeof AuthenticatedAiPsychologyRoute
  '/_authenticated/ai/settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/ai/trade-review': typeof AuthenticatedAiTradeReviewRoute
  '/_authenticated/challenges/history': typeof AuthenticatedChallengesHistoryRoute
  '/_authenticated/challenges/rewards': typeof AuthenticatedChallengesRewardsRoute
  '/_authenticated/leaderboard/country': typeof AuthenticatedLeaderboardCountryRoute
  '/_authenticated/leaderboard/friends': typeof AuthenticatedLeaderboardFriendsRoute
  '/_authenticated/leaderboard/global': typeof AuthenticatedLeaderboardGlobalRoute
  '/_authenticated/leaderboard/league': typeof AuthenticatedLeaderboardLeagueRoute
  '/_authenticated/market/alerts': typeof AuthenticatedMarketAlertsRoute
  '/_authenticated/market/providers': typeof AuthenticatedMarketProvidersRoute
  '/_authenticated/market/sessions': typeof AuthenticatedMarketSessionsRoute
  '/_authenticated/market/settings': typeof AuthenticatedMarketSettingsRoute
  '/_authenticated/market/symbols': typeof AuthenticatedMarketSymbolsRoute
  '/_authenticated/profile/$username': typeof AuthenticatedProfileUsernameRoute
  '/_authenticated/replay/library': typeof AuthenticatedReplayLibraryRoute
  '/_authenticated/replay/session': typeof AuthenticatedReplaySessionRoute
  '/_authenticated/replay/settings': typeof AuthenticatedReplaySettingsRoute
  '/_authenticated/replay/trades': typeof AuthenticatedReplayTradesRoute
  '/_authenticated/statistics/calendar': typeof AuthenticatedStatisticsCalendarRoute
  '/_authenticated/statistics/performance': typeof AuthenticatedStatisticsPerformanceRoute
  '/_authenticated/statistics/reports': typeof AuthenticatedStatisticsReportsRoute
  '/_authenticated/statistics/risk': typeof AuthenticatedStatisticsRiskRoute
  '/_authenticated/statistics/sessions': typeof AuthenticatedStatisticsSessionsRoute
  '/_authenticated/statistics/setups': typeof AuthenticatedStatisticsSetupsRoute
  '/_authenticated/strategies/$id': typeof AuthenticatedStrategiesIdRoute
  '/_authenticated/strategies/backtests': typeof AuthenticatedStrategiesBacktestsRoute
  '/_authenticated/strategies/create': typeof AuthenticatedStrategiesCreateRoute
  '/_authenticated/strategies/library': typeof AuthenticatedStrategiesLibraryRoute
  '/_authenticated/strategies/playbooks': typeof AuthenticatedStrategiesPlaybooksRoute
  '/_authenticated/strategies/settings': typeof AuthenticatedStrategiesSettingsRoute
  '/_authenticated/strategies/shared': typeof AuthenticatedStrategiesSharedRoute
  '/_authenticated/strategies/templates': typeof AuthenticatedStrategiesTemplatesRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/journal/share/$token': typeof JournalShareTokenRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/leaderboard/': typeof AuthenticatedLeaderboardIndexRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
  '/_authenticated/replay/': typeof AuthenticatedReplayIndexRoute
  '/_authenticated/statistics/': typeof AuthenticatedStatisticsIndexRoute
  '/_authenticated/strategies/': typeof AuthenticatedStrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/ai'
    | '/challenges'
    | '/dashboard'
    | '/journal'
    | '/leaderboard'
    | '/market'
    | '/paper-trading'
    | '/profile'
    | '/replay'
    | '/settings'
    | '/statistics'
    | '/strategies'
    | '/support'
    | '/users'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/challenges'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/feature-flags'
    | '/admin/journal'
    | '/admin/leaderboards'
    | '/admin/logs'
    | '/admin/market-data'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/trades'
    | '/admin/users'
    | '/ai/chat'
    | '/ai/dashboard'
    | '/ai/history'
    | '/ai/performance'
    | '/ai/playbooks'
    | '/ai/psychology'
    | '/ai/settings'
    | '/ai/trade-review'
    | '/challenges/history'
    | '/challenges/rewards'
    | '/leaderboard/country'
    | '/leaderboard/friends'
    | '/leaderboard/global'
    | '/leaderboard/league'
    | '/market/alerts'
    | '/market/providers'
    | '/market/sessions'
    | '/market/settings'
    | '/market/symbols'
    | '/profile/$username'
    | '/replay/library'
    | '/replay/session'
    | '/replay/settings'
    | '/replay/trades'
    | '/statistics/calendar'
    | '/statistics/performance'
    | '/statistics/reports'
    | '/statistics/risk'
    | '/statistics/sessions'
    | '/statistics/setups'
    | '/strategies/$id'
    | '/strategies/backtests'
    | '/strategies/create'
    | '/strategies/library'
    | '/strategies/playbooks'
    | '/strategies/settings'
    | '/strategies/shared'
    | '/strategies/templates'
    | '/api/ai/chat'
    | '/journal/share/$token'
    | '/admin/'
    | '/leaderboard/'
    | '/market/'
    | '/replay/'
    | '/statistics/'
    | '/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/achievements'
    | '/ai'
    | '/challenges'
    | '/dashboard'
    | '/journal'
    | '/paper-trading'
    | '/profile'
    | '/settings'
    | '/support'
    | '/users'
    | '/admin/achievements'
    | '/admin/announcements'
    | '/admin/challenges'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/feature-flags'
    | '/admin/journal'
    | '/admin/leaderboards'
    | '/admin/logs'
    | '/admin/market-data'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/storage'
    | '/admin/trades'
    | '/admin/users'
    | '/ai/chat'
    | '/ai/dashboard'
    | '/ai/history'
    | '/ai/performance'
    | '/ai/playbooks'
    | '/ai/psychology'
    | '/ai/settings'
    | '/ai/trade-review'
    | '/challenges/history'
    | '/challenges/rewards'
    | '/leaderboard/country'
    | '/leaderboard/friends'
    | '/leaderboard/global'
    | '/leaderboard/league'
    | '/market/alerts'
    | '/market/providers'
    | '/market/sessions'
    | '/market/settings'
    | '/market/symbols'
    | '/profile/$username'
    | '/replay/library'
    | '/replay/session'
    | '/replay/settings'
    | '/replay/trades'
    | '/statistics/calendar'
    | '/statistics/performance'
    | '/statistics/reports'
    | '/statistics/risk'
    | '/statistics/sessions'
    | '/statistics/setups'
    | '/strategies/$id'
    | '/strategies/backtests'
    | '/strategies/create'
    | '/strategies/library'
    | '/strategies/playbooks'
    | '/strategies/settings'
    | '/strategies/shared'
    | '/strategies/templates'
    | '/api/ai/chat'
    | '/journal/share/$token'
    | '/admin'
    | '/leaderboard'
    | '/market'
    | '/replay'
    | '/statistics'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/ai'
    | '/_authenticated/challenges'
    | '/_authenticated/dashboard'
    | '/_authenticated/journal'
    | '/_authenticated/leaderboard'
    | '/_authenticated/market'
    | '/_authenticated/paper-trading'
    | '/_authenticated/profile'
    | '/_authenticated/replay'
    | '/_authenticated/settings'
    | '/_authenticated/statistics'
    | '/_authenticated/strategies'
    | '/_authenticated/support'
    | '/_authenticated/users'
    | '/_authenticated/admin/achievements'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/challenges'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/feature-flags'
    | '/_authenticated/admin/journal'
    | '/_authenticated/admin/leaderboards'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/market-data'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/storage'
    | '/_authenticated/admin/trades'
    | '/_authenticated/admin/users'
    | '/_authenticated/ai/chat'
    | '/_authenticated/ai/dashboard'
    | '/_authenticated/ai/history'
    | '/_authenticated/ai/performance'
    | '/_authenticated/ai/playbooks'
    | '/_authenticated/ai/psychology'
    | '/_authenticated/ai/settings'
    | '/_authenticated/ai/trade-review'
    | '/_authenticated/challenges/history'
    | '/_authenticated/challenges/rewards'
    | '/_authenticated/leaderboard/country'
    | '/_authenticated/leaderboard/friends'
    | '/_authenticated/leaderboard/global'
    | '/_authenticated/leaderboard/league'
    | '/_authenticated/market/alerts'
    | '/_authenticated/market/providers'
    | '/_authenticated/market/sessions'
    | '/_authenticated/market/settings'
    | '/_authenticated/market/symbols'
    | '/_authenticated/profile/$username'
    | '/_authenticated/replay/library'
    | '/_authenticated/replay/session'
    | '/_authenticated/replay/settings'
    | '/_authenticated/replay/trades'
    | '/_authenticated/statistics/calendar'
    | '/_authenticated/statistics/performance'
    | '/_authenticated/statistics/reports'
    | '/_authenticated/statistics/risk'
    | '/_authenticated/statistics/sessions'
    | '/_authenticated/statistics/setups'
    | '/_authenticated/strategies/$id'
    | '/_authenticated/strategies/backtests'
    | '/_authenticated/strategies/create'
    | '/_authenticated/strategies/library'
    | '/_authenticated/strategies/playbooks'
    | '/_authenticated/strategies/settings'
    | '/_authenticated/strategies/shared'
    | '/_authenticated/strategies/templates'
    | '/api/ai/chat'
    | '/journal/share/$token'
    | '/_authenticated/admin/'
    | '/_authenticated/leaderboard/'
    | '/_authenticated/market/'
    | '/_authenticated/replay/'
    | '/_authenticated/statistics/'
    | '/_authenticated/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  JournalShareTokenRoute: typeof JournalShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/replay': {
      id: '/_authenticated/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof AuthenticatedReplayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/paper-trading': {
      id: '/_authenticated/paper-trading'
      path: '/paper-trading'
      fullPath: '/paper-trading'
      preLoaderRoute: typeof AuthenticatedPaperTradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategies/': {
      id: '/_authenticated/strategies/'
      path: '/'
      fullPath: '/strategies/'
      preLoaderRoute: typeof AuthenticatedStrategiesIndexRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/statistics/': {
      id: '/_authenticated/statistics/'
      path: '/'
      fullPath: '/statistics/'
      preLoaderRoute: typeof AuthenticatedStatisticsIndexRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/replay/': {
      id: '/_authenticated/replay/'
      path: '/'
      fullPath: '/replay/'
      preLoaderRoute: typeof AuthenticatedReplayIndexRouteImport
      parentRoute: typeof AuthenticatedReplayRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/leaderboard/': {
      id: '/_authenticated/leaderboard/'
      path: '/'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof AuthenticatedLeaderboardIndexRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/journal/share/$token': {
      id: '/journal/share/$token'
      path: '/journal/share/$token'
      fullPath: '/journal/share/$token'
      preLoaderRoute: typeof JournalShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategies/templates': {
      id: '/_authenticated/strategies/templates'
      path: '/templates'
      fullPath: '/strategies/templates'
      preLoaderRoute: typeof AuthenticatedStrategiesTemplatesRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/shared': {
      id: '/_authenticated/strategies/shared'
      path: '/shared'
      fullPath: '/strategies/shared'
      preLoaderRoute: typeof AuthenticatedStrategiesSharedRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/settings': {
      id: '/_authenticated/strategies/settings'
      path: '/settings'
      fullPath: '/strategies/settings'
      preLoaderRoute: typeof AuthenticatedStrategiesSettingsRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/playbooks': {
      id: '/_authenticated/strategies/playbooks'
      path: '/playbooks'
      fullPath: '/strategies/playbooks'
      preLoaderRoute: typeof AuthenticatedStrategiesPlaybooksRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/library': {
      id: '/_authenticated/strategies/library'
      path: '/library'
      fullPath: '/strategies/library'
      preLoaderRoute: typeof AuthenticatedStrategiesLibraryRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/create': {
      id: '/_authenticated/strategies/create'
      path: '/create'
      fullPath: '/strategies/create'
      preLoaderRoute: typeof AuthenticatedStrategiesCreateRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/backtests': {
      id: '/_authenticated/strategies/backtests'
      path: '/backtests'
      fullPath: '/strategies/backtests'
      preLoaderRoute: typeof AuthenticatedStrategiesBacktestsRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/strategies/$id': {
      id: '/_authenticated/strategies/$id'
      path: '/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof AuthenticatedStrategiesIdRouteImport
      parentRoute: typeof AuthenticatedStrategiesRoute
    }
    '/_authenticated/statistics/setups': {
      id: '/_authenticated/statistics/setups'
      path: '/setups'
      fullPath: '/statistics/setups'
      preLoaderRoute: typeof AuthenticatedStatisticsSetupsRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/statistics/sessions': {
      id: '/_authenticated/statistics/sessions'
      path: '/sessions'
      fullPath: '/statistics/sessions'
      preLoaderRoute: typeof AuthenticatedStatisticsSessionsRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/statistics/risk': {
      id: '/_authenticated/statistics/risk'
      path: '/risk'
      fullPath: '/statistics/risk'
      preLoaderRoute: typeof AuthenticatedStatisticsRiskRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/statistics/reports': {
      id: '/_authenticated/statistics/reports'
      path: '/reports'
      fullPath: '/statistics/reports'
      preLoaderRoute: typeof AuthenticatedStatisticsReportsRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/statistics/performance': {
      id: '/_authenticated/statistics/performance'
      path: '/performance'
      fullPath: '/statistics/performance'
      preLoaderRoute: typeof AuthenticatedStatisticsPerformanceRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/statistics/calendar': {
      id: '/_authenticated/statistics/calendar'
      path: '/calendar'
      fullPath: '/statistics/calendar'
      preLoaderRoute: typeof AuthenticatedStatisticsCalendarRouteImport
      parentRoute: typeof AuthenticatedStatisticsRoute
    }
    '/_authenticated/replay/trades': {
      id: '/_authenticated/replay/trades'
      path: '/trades'
      fullPath: '/replay/trades'
      preLoaderRoute: typeof AuthenticatedReplayTradesRouteImport
      parentRoute: typeof AuthenticatedReplayRoute
    }
    '/_authenticated/replay/settings': {
      id: '/_authenticated/replay/settings'
      path: '/settings'
      fullPath: '/replay/settings'
      preLoaderRoute: typeof AuthenticatedReplaySettingsRouteImport
      parentRoute: typeof AuthenticatedReplayRoute
    }
    '/_authenticated/replay/session': {
      id: '/_authenticated/replay/session'
      path: '/session'
      fullPath: '/replay/session'
      preLoaderRoute: typeof AuthenticatedReplaySessionRouteImport
      parentRoute: typeof AuthenticatedReplayRoute
    }
    '/_authenticated/replay/library': {
      id: '/_authenticated/replay/library'
      path: '/library'
      fullPath: '/replay/library'
      preLoaderRoute: typeof AuthenticatedReplayLibraryRouteImport
      parentRoute: typeof AuthenticatedReplayRoute
    }
    '/_authenticated/profile/$username': {
      id: '/_authenticated/profile/$username'
      path: '/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AuthenticatedProfileUsernameRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/market/symbols': {
      id: '/_authenticated/market/symbols'
      path: '/symbols'
      fullPath: '/market/symbols'
      preLoaderRoute: typeof AuthenticatedMarketSymbolsRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/market/settings': {
      id: '/_authenticated/market/settings'
      path: '/settings'
      fullPath: '/market/settings'
      preLoaderRoute: typeof AuthenticatedMarketSettingsRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/market/sessions': {
      id: '/_authenticated/market/sessions'
      path: '/sessions'
      fullPath: '/market/sessions'
      preLoaderRoute: typeof AuthenticatedMarketSessionsRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/market/providers': {
      id: '/_authenticated/market/providers'
      path: '/providers'
      fullPath: '/market/providers'
      preLoaderRoute: typeof AuthenticatedMarketProvidersRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/market/alerts': {
      id: '/_authenticated/market/alerts'
      path: '/alerts'
      fullPath: '/market/alerts'
      preLoaderRoute: typeof AuthenticatedMarketAlertsRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/leaderboard/league': {
      id: '/_authenticated/leaderboard/league'
      path: '/league'
      fullPath: '/leaderboard/league'
      preLoaderRoute: typeof AuthenticatedLeaderboardLeagueRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/leaderboard/global': {
      id: '/_authenticated/leaderboard/global'
      path: '/global'
      fullPath: '/leaderboard/global'
      preLoaderRoute: typeof AuthenticatedLeaderboardGlobalRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/leaderboard/friends': {
      id: '/_authenticated/leaderboard/friends'
      path: '/friends'
      fullPath: '/leaderboard/friends'
      preLoaderRoute: typeof AuthenticatedLeaderboardFriendsRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/leaderboard/country': {
      id: '/_authenticated/leaderboard/country'
      path: '/country'
      fullPath: '/leaderboard/country'
      preLoaderRoute: typeof AuthenticatedLeaderboardCountryRouteImport
      parentRoute: typeof AuthenticatedLeaderboardRoute
    }
    '/_authenticated/challenges/rewards': {
      id: '/_authenticated/challenges/rewards'
      path: '/rewards'
      fullPath: '/challenges/rewards'
      preLoaderRoute: typeof AuthenticatedChallengesRewardsRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/_authenticated/challenges/history': {
      id: '/_authenticated/challenges/history'
      path: '/history'
      fullPath: '/challenges/history'
      preLoaderRoute: typeof AuthenticatedChallengesHistoryRouteImport
      parentRoute: typeof AuthenticatedChallengesRoute
    }
    '/_authenticated/ai/trade-review': {
      id: '/_authenticated/ai/trade-review'
      path: '/trade-review'
      fullPath: '/ai/trade-review'
      preLoaderRoute: typeof AuthenticatedAiTradeReviewRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/settings': {
      id: '/_authenticated/ai/settings'
      path: '/settings'
      fullPath: '/ai/settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/psychology': {
      id: '/_authenticated/ai/psychology'
      path: '/psychology'
      fullPath: '/ai/psychology'
      preLoaderRoute: typeof AuthenticatedAiPsychologyRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/playbooks': {
      id: '/_authenticated/ai/playbooks'
      path: '/playbooks'
      fullPath: '/ai/playbooks'
      preLoaderRoute: typeof AuthenticatedAiPlaybooksRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/performance': {
      id: '/_authenticated/ai/performance'
      path: '/performance'
      fullPath: '/ai/performance'
      preLoaderRoute: typeof AuthenticatedAiPerformanceRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/history': {
      id: '/_authenticated/ai/history'
      path: '/history'
      fullPath: '/ai/history'
      preLoaderRoute: typeof AuthenticatedAiHistoryRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/dashboard': {
      id: '/_authenticated/ai/dashboard'
      path: '/dashboard'
      fullPath: '/ai/dashboard'
      preLoaderRoute: typeof AuthenticatedAiDashboardRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/ai/chat': {
      id: '/_authenticated/ai/chat'
      path: '/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedAiRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/trades': {
      id: '/_authenticated/admin/trades'
      path: '/trades'
      fullPath: '/admin/trades'
      preLoaderRoute: typeof AuthenticatedAdminTradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/storage': {
      id: '/_authenticated/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AuthenticatedAdminStorageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/market-data': {
      id: '/_authenticated/admin/market-data'
      path: '/market-data'
      fullPath: '/admin/market-data'
      preLoaderRoute: typeof AuthenticatedAdminMarketDataRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leaderboards': {
      id: '/_authenticated/admin/leaderboards'
      path: '/leaderboards'
      fullPath: '/admin/leaderboards'
      preLoaderRoute: typeof AuthenticatedAdminLeaderboardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/journal': {
      id: '/_authenticated/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AuthenticatedAdminJournalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/feature-flags': {
      id: '/_authenticated/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AuthenticatedAdminFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/challenges': {
      id: '/_authenticated/admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AuthenticatedAdminChallengesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/achievements': {
      id: '/_authenticated/admin/achievements'
      path: '/achievements'
      fullPath: '/admin/achievements'
      preLoaderRoute: typeof AuthenticatedAdminAchievementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAchievementsRoute: typeof AuthenticatedAdminAchievementsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminChallengesRoute: typeof AuthenticatedAdminChallengesRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminFeatureFlagsRoute: typeof AuthenticatedAdminFeatureFlagsRoute
  AuthenticatedAdminJournalRoute: typeof AuthenticatedAdminJournalRoute
  AuthenticatedAdminLeaderboardsRoute: typeof AuthenticatedAdminLeaderboardsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMarketDataRoute: typeof AuthenticatedAdminMarketDataRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStorageRoute: typeof AuthenticatedAdminStorageRoute
  AuthenticatedAdminTradesRoute: typeof AuthenticatedAdminTradesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAchievementsRoute: AuthenticatedAdminAchievementsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminChallengesRoute: AuthenticatedAdminChallengesRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminFeatureFlagsRoute: AuthenticatedAdminFeatureFlagsRoute,
  AuthenticatedAdminJournalRoute: AuthenticatedAdminJournalRoute,
  AuthenticatedAdminLeaderboardsRoute: AuthenticatedAdminLeaderboardsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminMarketDataRoute: AuthenticatedAdminMarketDataRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStorageRoute: AuthenticatedAdminStorageRoute,
  AuthenticatedAdminTradesRoute: AuthenticatedAdminTradesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAiRouteChildren {
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRoute
  AuthenticatedAiDashboardRoute: typeof AuthenticatedAiDashboardRoute
  AuthenticatedAiHistoryRoute: typeof AuthenticatedAiHistoryRoute
  AuthenticatedAiPerformanceRoute: typeof AuthenticatedAiPerformanceRoute
  AuthenticatedAiPlaybooksRoute: typeof AuthenticatedAiPlaybooksRoute
  AuthenticatedAiPsychologyRoute: typeof AuthenticatedAiPsychologyRoute
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedAiTradeReviewRoute: typeof AuthenticatedAiTradeReviewRoute
}

const AuthenticatedAiRouteChildren: AuthenticatedAiRouteChildren = {
  AuthenticatedAiChatRoute: AuthenticatedAiChatRoute,
  AuthenticatedAiDashboardRoute: AuthenticatedAiDashboardRoute,
  AuthenticatedAiHistoryRoute: AuthenticatedAiHistoryRoute,
  AuthenticatedAiPerformanceRoute: AuthenticatedAiPerformanceRoute,
  AuthenticatedAiPlaybooksRoute: AuthenticatedAiPlaybooksRoute,
  AuthenticatedAiPsychologyRoute: AuthenticatedAiPsychologyRoute,
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedAiTradeReviewRoute: AuthenticatedAiTradeReviewRoute,
}

const AuthenticatedAiRouteWithChildren = AuthenticatedAiRoute._addFileChildren(
  AuthenticatedAiRouteChildren,
)

interface AuthenticatedChallengesRouteChildren {
  AuthenticatedChallengesHistoryRoute: typeof AuthenticatedChallengesHistoryRoute
  AuthenticatedChallengesRewardsRoute: typeof AuthenticatedChallengesRewardsRoute
}

const AuthenticatedChallengesRouteChildren: AuthenticatedChallengesRouteChildren =
  {
    AuthenticatedChallengesHistoryRoute: AuthenticatedChallengesHistoryRoute,
    AuthenticatedChallengesRewardsRoute: AuthenticatedChallengesRewardsRoute,
  }

const AuthenticatedChallengesRouteWithChildren =
  AuthenticatedChallengesRoute._addFileChildren(
    AuthenticatedChallengesRouteChildren,
  )

interface AuthenticatedLeaderboardRouteChildren {
  AuthenticatedLeaderboardCountryRoute: typeof AuthenticatedLeaderboardCountryRoute
  AuthenticatedLeaderboardFriendsRoute: typeof AuthenticatedLeaderboardFriendsRoute
  AuthenticatedLeaderboardGlobalRoute: typeof AuthenticatedLeaderboardGlobalRoute
  AuthenticatedLeaderboardLeagueRoute: typeof AuthenticatedLeaderboardLeagueRoute
  AuthenticatedLeaderboardIndexRoute: typeof AuthenticatedLeaderboardIndexRoute
}

const AuthenticatedLeaderboardRouteChildren: AuthenticatedLeaderboardRouteChildren =
  {
    AuthenticatedLeaderboardCountryRoute: AuthenticatedLeaderboardCountryRoute,
    AuthenticatedLeaderboardFriendsRoute: AuthenticatedLeaderboardFriendsRoute,
    AuthenticatedLeaderboardGlobalRoute: AuthenticatedLeaderboardGlobalRoute,
    AuthenticatedLeaderboardLeagueRoute: AuthenticatedLeaderboardLeagueRoute,
    AuthenticatedLeaderboardIndexRoute: AuthenticatedLeaderboardIndexRoute,
  }

const AuthenticatedLeaderboardRouteWithChildren =
  AuthenticatedLeaderboardRoute._addFileChildren(
    AuthenticatedLeaderboardRouteChildren,
  )

interface AuthenticatedMarketRouteChildren {
  AuthenticatedMarketAlertsRoute: typeof AuthenticatedMarketAlertsRoute
  AuthenticatedMarketProvidersRoute: typeof AuthenticatedMarketProvidersRoute
  AuthenticatedMarketSessionsRoute: typeof AuthenticatedMarketSessionsRoute
  AuthenticatedMarketSettingsRoute: typeof AuthenticatedMarketSettingsRoute
  AuthenticatedMarketSymbolsRoute: typeof AuthenticatedMarketSymbolsRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
}

const AuthenticatedMarketRouteChildren: AuthenticatedMarketRouteChildren = {
  AuthenticatedMarketAlertsRoute: AuthenticatedMarketAlertsRoute,
  AuthenticatedMarketProvidersRoute: AuthenticatedMarketProvidersRoute,
  AuthenticatedMarketSessionsRoute: AuthenticatedMarketSessionsRoute,
  AuthenticatedMarketSettingsRoute: AuthenticatedMarketSettingsRoute,
  AuthenticatedMarketSymbolsRoute: AuthenticatedMarketSymbolsRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
}

const AuthenticatedMarketRouteWithChildren =
  AuthenticatedMarketRoute._addFileChildren(AuthenticatedMarketRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileUsernameRoute: typeof AuthenticatedProfileUsernameRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileUsernameRoute: AuthenticatedProfileUsernameRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedReplayRouteChildren {
  AuthenticatedReplayLibraryRoute: typeof AuthenticatedReplayLibraryRoute
  AuthenticatedReplaySessionRoute: typeof AuthenticatedReplaySessionRoute
  AuthenticatedReplaySettingsRoute: typeof AuthenticatedReplaySettingsRoute
  AuthenticatedReplayTradesRoute: typeof AuthenticatedReplayTradesRoute
  AuthenticatedReplayIndexRoute: typeof AuthenticatedReplayIndexRoute
}

const AuthenticatedReplayRouteChildren: AuthenticatedReplayRouteChildren = {
  AuthenticatedReplayLibraryRoute: AuthenticatedReplayLibraryRoute,
  AuthenticatedReplaySessionRoute: AuthenticatedReplaySessionRoute,
  AuthenticatedReplaySettingsRoute: AuthenticatedReplaySettingsRoute,
  AuthenticatedReplayTradesRoute: AuthenticatedReplayTradesRoute,
  AuthenticatedReplayIndexRoute: AuthenticatedReplayIndexRoute,
}

const AuthenticatedReplayRouteWithChildren =
  AuthenticatedReplayRoute._addFileChildren(AuthenticatedReplayRouteChildren)

interface AuthenticatedStatisticsRouteChildren {
  AuthenticatedStatisticsCalendarRoute: typeof AuthenticatedStatisticsCalendarRoute
  AuthenticatedStatisticsPerformanceRoute: typeof AuthenticatedStatisticsPerformanceRoute
  AuthenticatedStatisticsReportsRoute: typeof AuthenticatedStatisticsReportsRoute
  AuthenticatedStatisticsRiskRoute: typeof AuthenticatedStatisticsRiskRoute
  AuthenticatedStatisticsSessionsRoute: typeof AuthenticatedStatisticsSessionsRoute
  AuthenticatedStatisticsSetupsRoute: typeof AuthenticatedStatisticsSetupsRoute
  AuthenticatedStatisticsIndexRoute: typeof AuthenticatedStatisticsIndexRoute
}

const AuthenticatedStatisticsRouteChildren: AuthenticatedStatisticsRouteChildren =
  {
    AuthenticatedStatisticsCalendarRoute: AuthenticatedStatisticsCalendarRoute,
    AuthenticatedStatisticsPerformanceRoute:
      AuthenticatedStatisticsPerformanceRoute,
    AuthenticatedStatisticsReportsRoute: AuthenticatedStatisticsReportsRoute,
    AuthenticatedStatisticsRiskRoute: AuthenticatedStatisticsRiskRoute,
    AuthenticatedStatisticsSessionsRoute: AuthenticatedStatisticsSessionsRoute,
    AuthenticatedStatisticsSetupsRoute: AuthenticatedStatisticsSetupsRoute,
    AuthenticatedStatisticsIndexRoute: AuthenticatedStatisticsIndexRoute,
  }

const AuthenticatedStatisticsRouteWithChildren =
  AuthenticatedStatisticsRoute._addFileChildren(
    AuthenticatedStatisticsRouteChildren,
  )

interface AuthenticatedStrategiesRouteChildren {
  AuthenticatedStrategiesIdRoute: typeof AuthenticatedStrategiesIdRoute
  AuthenticatedStrategiesBacktestsRoute: typeof AuthenticatedStrategiesBacktestsRoute
  AuthenticatedStrategiesCreateRoute: typeof AuthenticatedStrategiesCreateRoute
  AuthenticatedStrategiesLibraryRoute: typeof AuthenticatedStrategiesLibraryRoute
  AuthenticatedStrategiesPlaybooksRoute: typeof AuthenticatedStrategiesPlaybooksRoute
  AuthenticatedStrategiesSettingsRoute: typeof AuthenticatedStrategiesSettingsRoute
  AuthenticatedStrategiesSharedRoute: typeof AuthenticatedStrategiesSharedRoute
  AuthenticatedStrategiesTemplatesRoute: typeof AuthenticatedStrategiesTemplatesRoute
  AuthenticatedStrategiesIndexRoute: typeof AuthenticatedStrategiesIndexRoute
}

const AuthenticatedStrategiesRouteChildren: AuthenticatedStrategiesRouteChildren =
  {
    AuthenticatedStrategiesIdRoute: AuthenticatedStrategiesIdRoute,
    AuthenticatedStrategiesBacktestsRoute:
      AuthenticatedStrategiesBacktestsRoute,
    AuthenticatedStrategiesCreateRoute: AuthenticatedStrategiesCreateRoute,
    AuthenticatedStrategiesLibraryRoute: AuthenticatedStrategiesLibraryRoute,
    AuthenticatedStrategiesPlaybooksRoute:
      AuthenticatedStrategiesPlaybooksRoute,
    AuthenticatedStrategiesSettingsRoute: AuthenticatedStrategiesSettingsRoute,
    AuthenticatedStrategiesSharedRoute: AuthenticatedStrategiesSharedRoute,
    AuthenticatedStrategiesTemplatesRoute:
      AuthenticatedStrategiesTemplatesRoute,
    AuthenticatedStrategiesIndexRoute: AuthenticatedStrategiesIndexRoute,
  }

const AuthenticatedStrategiesRouteWithChildren =
  AuthenticatedStrategiesRoute._addFileChildren(
    AuthenticatedStrategiesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAiRoute: typeof AuthenticatedAiRouteWithChildren
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRouteWithChildren
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRouteWithChildren
  AuthenticatedPaperTradingRoute: typeof AuthenticatedPaperTradingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedReplayRoute: typeof AuthenticatedReplayRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRouteWithChildren
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRouteWithChildren
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAiRoute: AuthenticatedAiRouteWithChildren,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRouteWithChildren,
  AuthenticatedMarketRoute: AuthenticatedMarketRouteWithChildren,
  AuthenticatedPaperTradingRoute: AuthenticatedPaperTradingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedReplayRoute: AuthenticatedReplayRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRouteWithChildren,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRouteWithChildren,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  JournalShareTokenRoute: JournalShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
